const ideas = [
     "Bikin lagu dari suara kipas angin.",
  "Ngoding sambil merem (challenge).",
  "Cari gambar random terus kasih caption kocak.",
  "Buat website palsu yang isinya cuma tombol jebakan.",
  "Pretend jadi alien dan rekam podcast.",
  "Review benda yang nggak butuh direview (misal: batu, sendok).",
  "Bikin skenario palsu kayak kamu orang kaya tapi diem-diem programmer.",
  "Tutorial ngawur cara ngoding pakai bahasa alien.",
  "Ngobrol sama chatbot AI dan pura-pura dia beneran sahabatmu.",
  "Buat 'iklan palsu' produk absurd (contoh: sabun anti galau).",
  "Kasih komentar lucu ke review Google Maps acak.",
  "Reka ulang adegan film tapi semua karakter jadi coding enthusiast.",
  "Bikin musik dari suara keyboard mechanical.",
  "Membaca kode JavaScript kayak baca puisi.",
  "Pura-pura jadi hacker tapi gagal terus.",
  "Bikin 'drama coding' dengan karakter fiksi.",
  "Bikin channel masak buat programmer (misalnya: 'masak mie sambil compile').",
  "Ngoding pakai kaki (challenge konyol).",
  "Bikin app paling nggak berguna sedunia.",
  "React to old memes tapi kasih reaksi super serius.",
  "Bikin konten 'sebelum vs sesudah ngoding'.",
  "Pakai green screen, pura-pura kamu coding di luar angkasa.",
  "Tutorial bikin website untuk alien yang mendarat ke Bumi.",
  "Video 'day in my life as a coder but I live in Minecraft'.",
  "Coding dengan suara Google Translate.",
  "Tulis kode sambil baca horoskop.",
  "Tebak kode ini ngapain? (pake script absurd).",
  "Unboxing keyboard tapi kayak unboxing iPhone.",
  "Reaksi temen saat lihat terminal hitam dan banyak teks.",
  "Coba bikin game pake kertas, terus bandingin sama versi digital.",
  "Buat aplikasi buat kucing — literally.",
  "Translate lagu jadi kode (contoh: lirik jadi comment).",
  "React ke bug coding kayak kamu lihat hantu.",
  "Tutorial HTML tapi dibuat kayak trailer film action.",
  "Interview palsu sama Bill Gates (pakai AI atau editan).",
  "Fake call dari Elon Musk ngajakin project coding bareng.",
  "Coding sambil pake sarung dan nyalain kipas — edisi ngoding warung.",
  "Ngejelasin konsep JavaScript ke anak TK.",
  "Website random generator: alasan kenapa kamu belum ngoding hari ini.",
  "Parodi TED Talk: 'Bagaimana Ctrl + Z Mengubah Hidup Saya'.",
  "Tutorial coding sambil main sulap.",
  "Kode kamu = mood kamu. Tunjukin bedanya lewat warna tema IDE.",
  "Bikin aplikasi yang tiap klik tombol muncul quotes nyebelin.",
  "React ke error coding kayak komentator sepak bola.",
  "Main truth or dare bareng terminal Linux.",
  "Ngoding di tempat aneh: WC, atap rumah, di bawah meja.",
  "Bikin bot yang cuma spam 'semangat ngoding' tiap 1 menit.",
  "Video lucu: 'Kode ini ditulis saat saya lapar.'",
  "Tantangan: coding pakai bahasa pemrograman yang kamu bikin sendiri.",
  "Kode sebagai puisi cinta buat CPU.",
  "Ga ngoding ga seru",
  "kapan kapan ngoding c++ ah",
  "kapan nya bisa jadi web developer"
    ];

    const facts = [
         "Otak manusia bisa menghasilkan listrik untuk menyalakan bola lampu kecil.",
         "Cacing bisa beregenerasi jadi dua jika dipotong (tergantung spesiesnya).",
         "Kata 'robot' berasal dari kata Slavia yang artinya 'pekerja paksa'.",
         "Air panas bisa membeku lebih cepat dari air dingin, disebut Efek Mpemba.",
         "Gurita punya tiga jantung dan darah berwarna biru.",
         "Keyboard QWERTY awalnya dibuat untuk memperlambat mengetik.",
         "NASA pernah secara tidak sengaja menghapus rekaman asli pendaratan di Bulan.",
         "Burung hantu tidak bisa menggerakkan matanya, jadi kepalanya yang diputar.",
         "Semut tidak pernah tidur, tapi mereka punya siklus istirahat.",
         "Lebah bisa mengenali wajah manusia.",
         "Kucing tidak bisa merasakan rasa manis.",
         "Di luar angkasa, air mata tidak bisa jatuh — malah membentuk bola di mata.",
  "Paus biru punya jantung sebesar mobil kecil.",
  "Satu sendok tanah bisa mengandung lebih banyak makhluk hidup daripada jumlah manusia di Bumi.",
  "Tanduk badak terbuat dari keratin, sama seperti kuku manusia.",
  "Ayam bisa mengingat lebih dari 100 wajah individu, baik ayam maupun manusia.",
  "Laba-laba bisa 'terbang' dengan menjatuhkan benang dan ditangkap angin, disebut ballooning.",
  "Beberapa pohon bisa 'berkomunikasi' lewat jaringan akar bawah tanah menggunakan jamur.",
  "Manusia berbagi sekitar 60% DNA dengan pisang.",
  "Jerapah tidur kurang dari 2 jam sehari.",
  "Bayi memiliki lebih banyak tulang dari orang dewasa — sekitar 300 saat lahir.",
  "Air liur manusia bisa mengisi dua kolam renang selama seumur hidup.",
  "Tikus tertawa saat digelitik (dalam frekuensi ultrasonik).",
  "Hiu sudah ada sebelum pohon tumbuh di Bumi.",
  "Beberapa kura-kura bisa bernapas lewat pantatnya.",
  "Awan cumulus biasa beratnya bisa mencapai 500.000 kg.",
  "Kupu-kupu bisa mencium bau dengan kaki mereka.",
  "Siput bisa tidur selama 3 tahun tanpa makan.",
  "Hati manusia bisa tumbuh kembali setelah sebagian besar diangkat.",
  "Burung kolibri adalah satu-satunya burung yang bisa terbang mundur.",
  "Unta menyimpan lemak di punuk, bukan air.",
  "Bintang laut tidak punya otak dan tidak punya darah.",
  "Manusia adalah satu-satunya spesies yang bisa menangis karena emosi.",
  "Ikan bisa mabuk jika berenang di air mengandung alkohol.",
  "Listrik bisa bergerak hampir secepat cahaya dalam konduktor tertentu.",
  "Sisik di kaki ayam mirip struktur dengan sisik buaya.",
  "Lumba-lumba punya nama panggilan sendiri yang digunakan oleh sesama lumba-lumba.",
  "Anjing bisa mencium emosi manusia melalui bau keringat dan hormon.",
  "Suhu di permukaan planet Venus lebih panas dari Merkurius, walaupun Venus lebih jauh dari Matahari.",
  "Jamur terbesar di dunia menutupi area lebih dari 2.000 hektar di Oregon, AS.",
  "Sinyal saraf dalam tubuh bisa melaju hingga 400 km/jam.",
  "Kupu-kupu minum air mata penyu untuk mendapatkan garam.",
  "Lebih banyak makhluk hidup di lautan daripada di daratan.",
  "Kelelawar selalu berbelok kiri saat keluar dari gua.",
  "Ada ubur-ubur yang bisa hidup abadi secara biologis (Turritopsis dohrnii).",
  "Telinga manusia tidak berhenti tumbuh sepanjang hidup.",
  "Tulang paha manusia lebih kuat dari beton.",
  "Zebra memiliki pola garis unik seperti sidik jari manusia.",
  "Air mata buaya benar-benar ada — mereka keluar saat makan, tapi bukan karena emosi.",
  "Tikus bisa bertahan tanpa air lebih lama dari unta.",
  "Tumbuhan Venus flytrap hanya bisa menutup beberapa kali sebelum mati.",
  "Planet Saturnus bisa mengapung di air (kalau ada kolam raksasa).",
  "Kuda laut jantan yang mengandung dan melahirkan anak.",
  "Beberapa spesies katak bisa membeku di musim dingin dan hidup kembali saat mencair.",
  "Bumi bukan planet yang paling bulat — itu adalah Venus.",
  "Kebanyakan debu di rumah berasal dari kulit mati manusia.",
  "Manusia bisa bertahan tanpa makan selama lebih dari sebulan, tapi tidak tanpa tidur.",
  "Mata manusia bisa membedakan sekitar 10 juta warna.",
  "Seekor kecoa bisa hidup selama seminggu tanpa kepala.",
  "Gigi adalah satu-satunya bagian tubuh yang tidak bisa memperbaiki diri.",
  "Lidah manusia terdiri dari 8 otot yang bekerja seperti tentakel.",
  "Mimpi bisa berlangsung hanya beberapa detik tapi terasa lama.",
  "Air kelapa bisa digunakan sebagai pengganti cairan infus darurat.",
  "Bintang Neutron bisa seukuran kota tapi massanya lebih berat dari Matahari.",
  "Pisang mengandung sedikit radioaktif alami (kalium-40).",
  "Kupu-kupu punya mata majemuk dengan ribuan lensa.",
  "Ubur-ubur tidak punya jantung, otak, atau tulang.",
  "Cahaya Matahari butuh sekitar 8 menit 20 detik untuk sampai ke Bumi.",
  "Hewan tercepat di Bumi adalah elang peregrine saat menyelam (389 km/jam).",
  "Kelinci tidak bisa muntah.",
  "Bayi manusia bisa mengenali suara ibunya sejak lahir.",
  "Kucing bisa mengeong hanya kepada manusia, bukan sesama kucing.",
  "Gajah bisa mengenali diri di cermin (tanda kecerdasan tinggi).",
  "Tikus bisa bersin jika mencium aroma mint.",
  "Gunung Everest bertambah tinggi sekitar 4 mm per tahun.",
  "Lidah jerapah bisa sepanjang 45-50 cm.",
  "Madu adalah satu-satunya makanan yang tidak pernah basi.",
  "Planet Uranus mengorbit Matahari dalam posisi miring hampir 90 derajat.",
  "Manusia bisa bertahan hanya beberapa menit tanpa oksigen, tapi bisa berjam-jam tanpa detak jantung jika dibekukan.",
  "Jangkrik bisa menghitung suhu dengan frekuensi suaranya.",
  "Burung flamingo berwarna merah muda karena makan udang.",
  "Ulat berubah total menjadi kupu-kupu, bahkan sistem sarafnya terurai lalu dibentuk ulang.",
  "Beberapa paus tidur dengan separuh otaknya tetap aktif agar bisa bernapas.",
  "Kucing punya lebih dari 20 otot hanya untuk menggerakkan telinganya.",
  "Planet Merkurius tidak punya atmosfer, jadi siang dan malam sangat ekstrem.",
  "Telinga manusia bisa mendengar suara antara 20 Hz hingga 20.000 Hz.",
  "Bebek punya suara yang tidak menghasilkan gema (walau ini masih kontroversial).",
  "Manusia bisa mengingat hingga 7±2 item dalam memori jangka pendek.",
  "Bayi memiliki refleks menyelam alami saat masuk ke dalam air.",
  "Planet Jupiter begitu besar, semua planet lain bisa muat di dalamnya.",
  "Burung pelikan bisa menyimpan air dan ikan hingga 13 liter dalam paruhnya.",
  "Ayam bisa bertelur tanpa dibuahi dan tetap menghasilkan telur.",
  "Bunga matahari bisa bergerak mengikuti arah matahari, disebut heliotropisme.",
  "Tikus bisa masuk lubang sekecil koin karena tubuhnya fleksibel.",
  "Laba-laba bisa menghasilkan jenis jaring berbeda untuk tujuan berbeda.",
  "Telinga burung hantu tidak simetris agar bisa mendengar arah suara lebih akurat.",
  "Seekor hiu bisa mencium darah dalam air dari jarak kilometer.",
  "Manusia memiliki lebih banyak bakteri di tubuhnya daripada sel tubuh itu sendiri.",
  "Kelelawar adalah satu-satunya mamalia yang bisa terbang.",
  "Gurita bisa membuka tutup toples dari dalam.",
  "Jantung ikan paus biru berdetak sekitar 5-10 kali per menit saat menyelam.",
  "Bayi lahir dengan kemampuan refleks menutup tangan saat disentuh — disebut refleks genggam."
    ];

    const kataQoutes = [
         "🌟 'Jangan menyerah hari ini, karena besok bisa jadi milikmu.' - Unknown",
         "💻 'Code is like humor. When you have to explain it, it's bad.' - Cory House",
         "❤️ 'Dicintai adalah hal terbaik yang bisa dirasakan manusia.' - Victor Hugo",
         "🌙 'Kadang, diam adalah suara dari hati yang terdalam.'",
         "If I have seen further it is by standing on the shoulders of Giants. — Isaac Newton",
         "Imagination is more important than knowledge. — Albert Einstein",
         "We must all face the choice between what is right and what is easy. — J.K. Rowling",
         "The more I study science, the more I believe in God. — Albert Einstein",
         "In the middle of difficulty lies opportunity. — Albert Einstein",
         "The best way to predict the future is to invent it. — Alan Kay",
         "I am become Death, the destroyer of worlds. — J. Robert Oppenheimer",
         "Science is a way of thinking much more than it is a body of knowledge. — Carl Sagan",
         "The important thing is not to stop questioning. — Albert Einstein",
         "Do not worry about your difficulties in Mathematics; I can assure you mine are still greater. — Albert Einstein",
         "Success is not final, failure is not fatal: It is the courage to continue that counts. — Winston Churchill",
        "The only way to do great work is to love what you do. — Steve Jobs",
       "Education is the most powerful weapon which you can use to change the world. — Nelson Mandela",
        "The true sign of intelligence is not knowledge but imagination. — Albert Einstein",
       "Life is really simple, but we insist on making it complicated. — Confucius",
        "Knowing is not enough; we must apply. Willing is not enough; we must do. — Johann Wolfgang von Goethe",
      "Do what you can, with what you have, where you are. — Theodore Roosevelt",
      "It does not matter how slowly you go as long as you do not stop. — Confucius",
      "The unexamined life is not worth living. — Socrates",
     "To be, or not to be, that is the question. — William Shakespeare",
     "In the end, we will remember not the words of our enemies, but the silence of our friends. — Martin Luther King Jr.",
     "The only thing we have to fear is fear itself. — Franklin D. Roosevelt",
     "Be the change that you wish to see in the world. — Mahatma Gandhi",
  "What we think, we become. — Buddha",
  "An investment in knowledge pays the best interest. — Benjamin Franklin",
  "The journey of a thousand miles begins with one step. — Lao Tzu",
  "The only limit to our realization of tomorrow will be our doubts of today. — Franklin D. Roosevelt",
  "If you want to live a happy life, tie it to a goal, not to people or things. — Albert Einstein",
  "The best revenge is massive success. — Frank Sinatra",
  "It always seems impossible until it's done. — Nelson Mandela",
  "In the middle of every difficulty lies opportunity. — Albert Einstein",
  "Great minds discuss ideas; average minds discuss events; small minds discuss people. — Eleanor Roosevelt",
  "Don't watch the clock; do what it does. Keep going. — Sam Levenson",
  "Happiness is not something ready made. It comes from your own actions. — Dalai Lama",
  "The only true wisdom is in knowing you know nothing. — Socrates",
  "A person who never made a mistake never tried anything new. — Albert Einstein",
  "I think, therefore I am. — René Descartes",
  "To improve is to change; to be perfect is to change often. — Winston Churchill",
  "Life is 10% what happens to us and 90% how we react to it. — Charles R. Swindoll",
  "Try not to become a man of success, but rather try to become a man of value. — Albert Einstein",
  "Success usually comes to those who are too busy to be looking for it. — Henry David Thoreau",
  "The mind is everything. What you think you become. — Buddha",
  "Do not go where the path may lead, go instead where there is no path and leave a trail. — Ralph Waldo Emerson",
  "I have no special talent. I am only passionately curious. — Albert Einstein",
  "What you get by achieving your goals is not as important as what you become by achieving your goals. — Zig Ziglar",
  "Your time is limited, so don’t waste it living someone else’s life. — Steve Jobs",
  "The best way out is always through. — Robert Frost",
  "Believe you can and you're halfway there. — Theodore Roosevelt",
  "Be yourself; everyone else is already taken. — Oscar Wilde",
  "The harder the conflict, the greater the triumph. — George Washington",
  "The future belongs to those who prepare for it today. — Malcolm X",
  "Life isn’t about finding yourself. Life is about creating yourself. — George Bernard Shaw",
  "It is never too late to be what you might have been. — George Eliot",
  "Act as if what you do makes a difference. It does. — William James",
  "Everything you’ve ever wanted is on the other side of fear. — George Addair",
  "Do one thing every day that scares you. — Eleanor Roosevelt",
  "What lies behind us and what lies before us are tiny matters compared to what lies within us. — Ralph Waldo Emerson",
  "The power of imagination makes us infinite. — John Muir",
  "Only those who dare to fail greatly can ever achieve greatly. — Robert F. Kennedy",
  "You miss 100% of the shots you don’t take. — Wayne Gretzky",
  "It is our choices that show what we truly are, far more than our abilities. — J.K. Rowling",
  "Challenges are what make life interesting and overcoming them is what makes life meaningful. — Joshua J. Marine",
  "Success is stumbling from failure to failure with no loss of enthusiasm. — Winston Churchill",
  "The best way to find yourself is to lose yourself in the service of others. — Mahatma Gandhi",
  "Don’t count the days, make the days count. — Muhammad Ali",
  "The only way to have a friend is to be one. — Ralph Waldo Emerson",
  "A journey is best measured in friends, rather than miles. — Tim Cahill",
  "Peace begins with a smile. — Mother Teresa",
  "If you want to go fast, go alone. If you want to go far, go together. — African Proverb",
  "Education is not preparation for life; education is life itself. — John Dewey",
  "The secret of getting ahead is getting started. — Mark Twain",
  "Innovation distinguishes between a leader and a follower. — Steve Jobs",
  "Life is like riding a bicycle. To keep your balance you must keep moving. — Albert Einstein",
  "Imagination rules the world. — Napoleon Bonaparte",
  "The greatest glory in living lies not in never falling, but in rising every time we fall. — Nelson Mandela",
  "You must be the change you wish to see in the world. — Mahatma Gandhi",
  "A man who dares to waste one hour of time has not discovered the value of life. — Charles Darwin",
  "Don’t let yesterday take up too much of today. — Will Rogers",
  "The only thing necessary for the triumph of evil is for good men to do nothing. — Edmund Burke",
  "You can’t use up creativity. The more you use, the more you have. — Maya Angelou",
  "Try not to become a man of success but rather try to become a man of value. — Albert Einstein",
  "What we achieve inwardly will change outer reality. — Plutarch",
  "Life shrinks or expands in proportion to one’s courage. — Anaïs Nin",
  "The only real mistake is the one from which we learn nothing. — Henry Ford",
  "Do what is right, not what is easy nor what is popular. — Roy T. Bennett",
  "Happiness depends upon ourselves. — Aristotle",
  "The greatest wealth is to live content with little. — Plato",
  "Genius is one percent inspiration and ninety-nine percent perspiration. — Thomas Edison",
  "Success is getting what you want. Happiness is wanting what you get. — Dale Carnegie",
  "Keep your face always toward the sunshine—and shadows will fall behind you. — Walt Whitman",
  "It’s not whether you get knocked down, it’s whether you get up. — Vince Lombardi",
  "The difference between ordinary and extraordinary is that little extra. — Jimmy Johnson",
  "You only live once, but if you do it right, once is enough. — Mae West",
  "To succeed in life, you need two things: ignorance and confidence. — Mark Twain",
  "The mind is like a parachute. It doesn’t work if it isn’t open. — Frank Zappa"
    ];

    const texts = [
      "Hallo selamat datang di website saya!",
      "Ide random yang seru 🎲",
      "Tempat kamu cari hiburan 🕹️",
      "Fakta unik tiap hari 📚",
      "Qoutes yang bikin mikir 💡",
      "Kira kira ngoding apa ya biar seru",
      "Bagaimana sih cara jadi orang sukses?",
      "Imagination is more important than knowledge. -Albert Einstein",
      "Stay hungry, stay foolish. -Steve jobs",
      "The quieter you become, the more you able to hear",
    ];
    
   const typingElement = document.getElementById("typing");

      let textIndex = 0;
      let charIndex = 0;
      let isDeleting = false;

  function type() {
     const currentText = texts[textIndex];
     const displayedText = currentText.substring(0, charIndex);
     typingElement.textContent = displayedText;

     if (!isDeleting && charIndex < currentText.length) {
       charIndex++;
       setTimeout(type, 80); 
    } else if (isDeleting && charIndex > 0) {
       charIndex--;
       setTimeout(type, 30); 
     } else {
        if (!isDeleting) {
          isDeleting = true;
          setTimeout(type, 3000); 
      } else {
        isDeleting = false;
        textIndex = (textIndex + 1) % texts.length;
        setTimeout(type, 500); 
    }
  }
}

window.addEventListener("DOMContentLoaded", () => {
  type();
});

    function generateIdea() {
      const idea = ideas[Math.floor(Math.random() * ideas.length)];
      document.getElementById("random-idea").textContent = idea;
    }

    function generateFact() {
      const fact = facts[Math.floor(Math.random() * facts.length)];
      document.getElementById("fun-fact").textContent = fact;
    }

    function generateKata() {
      const kata = kataQoutes[Math.floor(Math.random() * kataQoutes.length)];
      document.getElementById("kata").textContent = kata;
    }

   